apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashresponder-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashresponder
  
  template:
    metadata:
      labels:
        app: hashresponder
    spec:
      containers:
      - name: hashresponder
        image: wettsti/hash-responder:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5050