apiVersion: v1
kind: Service
metadata:
  name: hashresponder-service
spec:
  type: LoadBalancer
  selector:
    app: hashresponder
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
