apiVersion: apps/v1
kind: Deployment
metadata:
  name: guidlogger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guidlogger
  template:
    metadata:
      labels:
        app: guidlogger
    spec:
      containers:
      - name: guidlogger
        image: wettsti/guid-logger:0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
