apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
      - name: hashgenerator
        image: wettsti/hash-generator:0.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
